title = "Amanda Ernar"
baseURL = "https://amandaernar.github.io/blog"
languageCode = "en-us"
theme = "gohugo-theme-ananke"
themesDir = "themes"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "site-logo.png"
  site_logo = "site-logo.png"
  description = "The last theme you'll ever need. Maybe."
  youtube = "https://www.youtube.com/channel/UC9kXxtdbkLEoX1TwBr9GTPA?"
  github = "https://github.com/amandaernar"
  rss = ""
  # http://tachyons.io/docs/themes/skins/
  background_color_class = "bg-blue"
  featured_image = "/images/homepage.jpg"
  recent_posts_number = 4