baseURL = "http://example.org/blog"
languageCode = "en-us"
title = "Amanda's sick website"
theme="archie"
copyright = "© Amanda Ernar"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
publishDir = "docs"

[params]
	mode="auto"
	useCDN=false
	subtitle = "aspiring author"

[[params.social]]
name = "YouTube"
icon = "youtube"
url = "https://www.youtube.com/channel/UC9kXxtdbkLEoX1TwBr9GTPA"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://www.github.com/AmandaErnar"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3
